# Generated by Django 3.2.2 on 2021-06-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210620_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
